name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        REACT_APP_UNSPLASH_ACCESS_KEY: ${{ secrets.REACT_APP_UNSPLASH_ACCESS_KEY }}
        REACT_APP_UNSPLASH_SCREAT_KEY: ${{ secrets.REACT_APP_UNSPLASH_SCREAT_KEY }}
        REACT_APP_UNSPLASH_CALL_BACK_URL:  ${{ secrets.REACT_APP_UNSPLASH_CALL_BACK_URL }}

      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
